version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements.txt
      - sls deploy --stage=${CODEBUILD_RESOLVED_SOURCE_VERSION}
